public class Testexception {
	public static void main(String[] args) {
		try
		{
			int i=1/0;
			System.out.println("enter the block exceuted");
		}
	catch(ArithmeticException a)
		{
		System.out.println("excuted");
		
		}
		

	}
	}

